# Generated by Django 4.2.6 on 2023-11-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0002_alter_menuitem_inventory_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.SlugField(),
        ),
    ]
