# Generated by Django 4.1.3 on 2023-10-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menu_item_description_alter_menu_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(),
        ),
    ]
