# Generated by Django 4.2.6 on 2023-10-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_menuitems_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='course',
            new_name='category',
        ),
    ]
