# Generated by Django 4.2.6 on 2023-10-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_rename_course_menuitems_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='name',
            new_name='itemname',
        ),
    ]
